# Setting these variables will automatically connect board to WiFi on boot
CIRCUITPY_WIFI_SSID="Your WiFi SSID Here"
CIRCUITPY_WIFI_PASSWORD="Your WiFi Password Here"

# MQTT integration.
# Leave the Broker IP empty to disable the MQTT functionality.
MQTT_BROKER_IP=""
MQTT_BROKER_PORT=1883
MQTT_USERNAME="username"
MQTT_PASSWORD="password"

# DistantSignal Configuration for this panel.
MQTT_TURNOUT="t330"

# Google Analytics 4 Configuration.
# Leave any field empty to disable the Analytics functionality.
GA4_CLIENT_ID=""
GA4_MEASURE_ID=""
GA4_API_SECRET=""
